Exod\PortfolioBundle\Entity\Actualite:
  type: entity
  repositoryClass: Exod\PortfolioBundle\Repository\ActualiteRepository
  table: actualite
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    texte:
      type: text
      nullable: false
    date:
      type: date
      nullable: false
  oneToOne:
    idarticle:
      targetEntity: Article
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        idArticle:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
