Exod\PortfolioBundle\Entity\Image:
  type: entity
  repositoryClass: Exod\PortfolioBundle\Repository\ImageRepository
  table: image
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    nom:
      type: string
      length: 45
      fixed: false
      nullable: false
    path:
      type: string
      length: 90
      fixed: false
      nullable: false
    format:
      type: string
      length: 45
      fixed: false
      nullable: false
    date:
      type: date
      nullable: false
  oneToOne:
    idprojet:
      targetEntity: Projet
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        idProjet:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
