projet:
    pattern:  /
    defaults: { _controller: "ExodPortfolioBundle:Projet:index" }

projet_show:
    pattern:  /{id}/show
    defaults: { _controller: "ExodPortfolioBundle:Projet:show" }

projet_new:
    pattern:  /new
    defaults: { _controller: "ExodPortfolioBundle:Projet:new" }

projet_create:
    pattern:  /create
    defaults: { _controller: "ExodPortfolioBundle:Projet:create" }
    requirements: { _method: post }

projet_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ExodPortfolioBundle:Projet:edit" }

projet_update:
    pattern:  /{id}/update
    defaults: { _controller: "ExodPortfolioBundle:Projet:update" }
    requirements: { _method: post }

projet_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ExodPortfolioBundle:Projet:delete" }
    requirements: { _method: post }
