parameters:
#    exod_portfolio.example.class: Exod\PortfolioBundle\Example

services:
#    exod_portfolio.example:
#        class: %exod_portfolio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
